export interface FoodPreset {
  name: string;
  emoji: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export interface PresetCategory {
  label: string;
  emoji: string;
  items: FoodPreset[];
}

// Approximate values per typical serving/plate
export const FOOD_PRESET_CATEGORIES: PresetCategory[] = [
  {
    label: 'Rice & Noodles',
    emoji: '🍚',
    items: [
      { name: 'Pad Thai', emoji: '🍜', calories: 450, protein: 18, carbs: 55, fat: 16 },
      { name: 'Pad See Ew', emoji: '🍜', calories: 480, protein: 20, carbs: 58, fat: 16 },
      { name: 'Pad Kra Pao + Rice', emoji: '🍚', calories: 550, protein: 28, carbs: 60, fat: 18 },
      { name: 'Khao Pad (Fried Rice)', emoji: '🍚', calories: 500, protein: 16, carbs: 62, fat: 18 },
      { name: 'Khao Man Gai', emoji: '🍗', calories: 580, protein: 32, carbs: 55, fat: 22 },
      { name: 'Khao Moo Daeng', emoji: '🍚', calories: 520, protein: 30, carbs: 58, fat: 14 },
      { name: 'Boat Noodles', emoji: '🍜', calories: 350, protein: 22, carbs: 40, fat: 10 },
      { name: 'Pad Woon Sen', emoji: '🍜', calories: 380, protein: 15, carbs: 48, fat: 12 },
      { name: 'Rad Na', emoji: '🍜', calories: 460, protein: 22, carbs: 52, fat: 16 },
      { name: 'Kuay Teaw (Noodle Soup)', emoji: '🍜', calories: 380, protein: 24, carbs: 42, fat: 10 },
    ],
  },
  {
    label: 'Curries & Soups',
    emoji: '🍛',
    items: [
      { name: 'Green Curry + Rice', emoji: '🟢', calories: 550, protein: 24, carbs: 55, fat: 24 },
      { name: 'Red Curry + Rice', emoji: '🔴', calories: 530, protein: 22, carbs: 54, fat: 22 },
      { name: 'Massaman Curry + Rice', emoji: '🍛', calories: 620, protein: 26, carbs: 58, fat: 28 },
      { name: 'Panang Curry + Rice', emoji: '🍛', calories: 560, protein: 25, carbs: 52, fat: 26 },
      { name: 'Tom Yum Goong', emoji: '🍲', calories: 200, protein: 20, carbs: 12, fat: 8 },
      { name: 'Tom Kha Gai', emoji: '🍲', calories: 300, protein: 18, carbs: 10, fat: 22 },
      { name: 'Gaeng Jued (Clear Soup)', emoji: '🍲', calories: 150, protein: 12, carbs: 10, fat: 6 },
    ],
  },
  {
    label: 'Stir-fry & Sides',
    emoji: '🥘',
    items: [
      { name: 'Gai Pad Med Mamuang', emoji: '🥜', calories: 420, protein: 28, carbs: 20, fat: 26 },
      { name: 'Larb Moo', emoji: '🥗', calories: 280, protein: 26, carbs: 8, fat: 16 },
      { name: 'Som Tam', emoji: '🥗', calories: 120, protein: 4, carbs: 18, fat: 4 },
      { name: 'Kai Jeow (Thai Omelette)', emoji: '🍳', calories: 300, protein: 16, carbs: 4, fat: 24 },
      { name: 'Moo Ping (Grilled Pork)', emoji: '🍢', calories: 250, protein: 22, carbs: 10, fat: 14 },
      { name: 'Gai Yang (Grilled Chicken)', emoji: '🍗', calories: 320, protein: 34, carbs: 6, fat: 18 },
      { name: 'Steamed Rice (1 plate)', emoji: '🍚', calories: 250, protein: 5, carbs: 55, fat: 1 },
      { name: 'Sticky Rice (1 portion)', emoji: '🍚', calories: 200, protein: 4, carbs: 44, fat: 0 },
    ],
  },
  {
    label: 'Drinks & Desserts',
    emoji: '🧋',
    items: [
      { name: 'Thai Iced Tea', emoji: '🧋', calories: 200, protein: 2, carbs: 38, fat: 5 },
      { name: 'Thai Iced Coffee', emoji: '☕', calories: 180, protein: 2, carbs: 32, fat: 5 },
      { name: 'Mango Sticky Rice', emoji: '🥭', calories: 400, protein: 5, carbs: 72, fat: 12 },
      { name: 'Roti + Condensed Milk', emoji: '🫓', calories: 350, protein: 6, carbs: 48, fat: 16 },
      { name: 'Kanom Buang (Crispy Crepe)', emoji: '🥞', calories: 150, protein: 3, carbs: 22, fat: 6 },
    ],
  },
  {
    label: '7-Eleven Meals',
    emoji: '🏪',
    items: [
      { name: '7-11 Toasted Ham & Cheese', emoji: '🥪', calories: 280, protein: 14, carbs: 28, fat: 12 },
      { name: '7-11 Toasted Tuna', emoji: '🥪', calories: 300, protein: 16, carbs: 30, fat: 12 },
      { name: '7-11 Toasted Crab Stick', emoji: '🥪', calories: 260, protein: 10, carbs: 30, fat: 10 },
      { name: '7-11 Croissant Ham Cheese', emoji: '🥐', calories: 320, protein: 12, carbs: 28, fat: 18 },
      { name: '7-11 Chicken Teriyaki Bento', emoji: '🍱', calories: 520, protein: 24, carbs: 68, fat: 14 },
      { name: '7-11 Pad Kra Pao Bento', emoji: '🍱', calories: 550, protein: 22, carbs: 65, fat: 18 },
      { name: '7-11 Pork Tonkatsu Bento', emoji: '🍱', calories: 580, protein: 20, carbs: 70, fat: 20 },
      { name: '7-11 Green Curry Rice Bento', emoji: '🍱', calories: 500, protein: 18, carbs: 62, fat: 16 },
      { name: '7-11 Omurice Bento', emoji: '🍱', calories: 480, protein: 16, carbs: 60, fat: 16 },
      { name: '7-11 Salmon Onigiri', emoji: '🍙', calories: 180, protein: 8, carbs: 30, fat: 3 },
      { name: '7-11 Tuna Mayo Onigiri', emoji: '🍙', calories: 200, protein: 8, carbs: 28, fat: 6 },
      { name: '7-11 Chicken Onigiri', emoji: '🍙', calories: 190, protein: 9, carbs: 28, fat: 4 },
      { name: '7-11 Shrimp Tempura Onigiri', emoji: '🍙', calories: 195, protein: 7, carbs: 32, fat: 4 },
      { name: '7-11 Salapao Moo (Pork Bun)', emoji: '🫓', calories: 220, protein: 10, carbs: 30, fat: 6 },
      { name: '7-11 Salapao Sai Kai Kem', emoji: '🫓', calories: 250, protein: 8, carbs: 32, fat: 10 },
      { name: '7-11 Salapao Custard', emoji: '🫓', calories: 230, protein: 5, carbs: 36, fat: 8 },
      { name: '7-11 Hot Dog (regular)', emoji: '🌭', calories: 280, protein: 10, carbs: 28, fat: 14 },
      { name: '7-11 Big Bite Sausage', emoji: '🌭', calories: 350, protein: 14, carbs: 30, fat: 18 },
      { name: '7-11 Fried Chicken Wing (2pc)', emoji: '🍗', calories: 320, protein: 20, carbs: 16, fat: 20 },
      { name: '7-11 Mama Cup Noodle', emoji: '🍜', calories: 300, protein: 7, carbs: 40, fat: 12 },
    ],
  },
  {
    label: '7-Eleven Drinks & Snacks',
    emoji: '🥤',
    items: [
      { name: '7-11 Iced Coffee (All Cafe)', emoji: '☕', calories: 120, protein: 3, carbs: 18, fat: 4 },
      { name: '7-11 Latte (All Cafe)', emoji: '☕', calories: 150, protein: 5, carbs: 20, fat: 5 },
      { name: '7-11 Mocha (All Cafe)', emoji: '☕', calories: 200, protein: 5, carbs: 30, fat: 6 },
      { name: '7-11 Matcha Latte (All Cafe)', emoji: '🍵', calories: 180, protein: 4, carbs: 28, fat: 5 },
      { name: '7-11 Cocoa (All Cafe)', emoji: '🍫', calories: 210, protein: 5, carbs: 32, fat: 7 },
      { name: '7-11 Slurpee (medium)', emoji: '🥤', calories: 180, protein: 0, carbs: 46, fat: 0 },
      { name: '7-11 Banana Cake', emoji: '🍰', calories: 280, protein: 4, carbs: 40, fat: 12 },
      { name: '7-11 Choco Lava', emoji: '🍫', calories: 300, protein: 5, carbs: 42, fat: 14 },
      { name: '7-11 Egg Custard Bread', emoji: '🍞', calories: 260, protein: 6, carbs: 36, fat: 10 },
      { name: '7-11 Butter Toast (2pc)', emoji: '🍞', calories: 220, protein: 4, carbs: 30, fat: 10 },
      { name: '7-11 Yogurt Drink', emoji: '🥛', calories: 140, protein: 4, carbs: 26, fat: 2 },
      { name: '7-11 Protein Milk', emoji: '🥛', calories: 160, protein: 20, carbs: 14, fat: 2 },
    ],
  },
  {
    label: 'McDonald\'s',
    emoji: '🍔',
    items: [
      { name: 'McD Big Mac', emoji: '🍔', calories: 550, protein: 25, carbs: 45, fat: 30 },
      { name: 'McD McChicken', emoji: '🍔', calories: 400, protein: 14, carbs: 40, fat: 22 },
      { name: 'McD Quarter Pounder', emoji: '🍔', calories: 520, protein: 30, carbs: 40, fat: 26 },
      { name: 'McD Double Cheeseburger', emoji: '🍔', calories: 450, protein: 25, carbs: 34, fat: 24 },
      { name: 'McD Samurai Pork Burger', emoji: '🍔', calories: 480, protein: 22, carbs: 42, fat: 22 },
      { name: 'McD Spicy Chicken', emoji: '🍔', calories: 450, protein: 18, carbs: 44, fat: 22 },
      { name: 'McD Chicken McNuggets (6pc)', emoji: '🍗', calories: 280, protein: 14, carbs: 18, fat: 16 },
      { name: 'McD Chicken McNuggets (9pc)', emoji: '🍗', calories: 420, protein: 21, carbs: 27, fat: 24 },
      { name: 'McD French Fries (M)', emoji: '🍟', calories: 340, protein: 4, carbs: 44, fat: 16 },
      { name: 'McD French Fries (L)', emoji: '🍟', calories: 490, protein: 6, carbs: 64, fat: 23 },
      { name: 'McD Egg McMuffin', emoji: '🍳', calories: 300, protein: 17, carbs: 26, fat: 13 },
      { name: 'McD Pork Sausage McMuffin', emoji: '🍳', calories: 400, protein: 16, carbs: 28, fat: 24 },
      { name: 'McD McFlurry Oreo', emoji: '🍦', calories: 340, protein: 8, carbs: 52, fat: 12 },
      { name: 'McD Cone', emoji: '🍦', calories: 150, protein: 4, carbs: 24, fat: 4 },
      { name: 'McD Apple Pie', emoji: '🥧', calories: 250, protein: 2, carbs: 32, fat: 14 },
    ],
  },
  {
    label: 'KFC',
    emoji: '🍗',
    items: [
      { name: 'KFC Original Chicken (1pc)', emoji: '🍗', calories: 320, protein: 22, carbs: 12, fat: 22 },
      { name: 'KFC Hot & Crispy (1pc)', emoji: '🍗', calories: 350, protein: 20, carbs: 16, fat: 24 },
      { name: 'KFC Chicken Strips (3pc)', emoji: '🍗', calories: 380, protein: 26, carbs: 20, fat: 22 },
      { name: 'KFC Zinger Burger', emoji: '🍔', calories: 480, protein: 22, carbs: 42, fat: 24 },
      { name: 'KFC Colonel Burger', emoji: '🍔', calories: 450, protein: 20, carbs: 40, fat: 22 },
      { name: 'KFC Twister Wrap', emoji: '🌯', calories: 420, protein: 18, carbs: 38, fat: 22 },
      { name: 'KFC Coleslaw', emoji: '🥗', calories: 150, protein: 1, carbs: 14, fat: 10 },
      { name: 'KFC Mashed Potato + Gravy', emoji: '🥔', calories: 130, protein: 2, carbs: 18, fat: 5 },
      { name: 'KFC Corn on the Cob', emoji: '🌽', calories: 140, protein: 4, carbs: 26, fat: 3 },
      { name: 'KFC Rice (1 serving)', emoji: '🍚', calories: 260, protein: 5, carbs: 56, fat: 1 },
      { name: 'KFC Egg Tart', emoji: '🥧', calories: 200, protein: 4, carbs: 22, fat: 10 },
    ],
  },
  {
    label: 'Burger King',
    emoji: '🍔',
    items: [
      { name: 'BK Whopper', emoji: '🍔', calories: 660, protein: 28, carbs: 49, fat: 40 },
      { name: 'BK Whopper Jr', emoji: '🍔', calories: 310, protein: 13, carbs: 27, fat: 18 },
      { name: 'BK Double Cheeseburger', emoji: '🍔', calories: 380, protein: 22, carbs: 28, fat: 20 },
      { name: 'BK Chicken Royale', emoji: '🍔', calories: 530, protein: 22, carbs: 48, fat: 28 },
      { name: 'BK Fish Burger', emoji: '🐟', calories: 400, protein: 16, carbs: 40, fat: 18 },
      { name: 'BK Onion Rings (M)', emoji: '🧅', calories: 320, protein: 4, carbs: 40, fat: 16 },
      { name: 'BK French Fries (M)', emoji: '🍟', calories: 340, protein: 4, carbs: 44, fat: 16 },
      { name: 'BK Chicken Nuggets (6pc)', emoji: '🍗', calories: 260, protein: 12, carbs: 16, fat: 16 },
    ],
  },
  {
    label: 'Pizza Company',
    emoji: '🍕',
    items: [
      { name: 'Pizza Co. Super Supreme (1 slice)', emoji: '🍕', calories: 280, protein: 12, carbs: 30, fat: 12 },
      { name: 'Pizza Co. Hawaian (1 slice)', emoji: '🍕', calories: 240, protein: 10, carbs: 30, fat: 8 },
      { name: 'Pizza Co. Seafood Deluxe (1 slice)', emoji: '🍕', calories: 260, protein: 12, carbs: 28, fat: 10 },
      { name: 'Pizza Co. Pepperoni (1 slice)', emoji: '🍕', calories: 270, protein: 12, carbs: 28, fat: 12 },
      { name: 'Pizza Co. Chicken Wings (6pc)', emoji: '🍗', calories: 420, protein: 28, carbs: 16, fat: 28 },
      { name: 'Pizza Co. Garlic Bread (2pc)', emoji: '🍞', calories: 200, protein: 4, carbs: 28, fat: 8 },
      { name: 'Pizza Co. Spaghetti Carbonara', emoji: '🍝', calories: 520, protein: 18, carbs: 58, fat: 22 },
      { name: 'Pizza Co. Spaghetti Bolognese', emoji: '🍝', calories: 480, protein: 20, carbs: 56, fat: 18 },
    ],
  },
  {
    label: 'MK Restaurant',
    emoji: '🫕',
    items: [
      { name: 'MK Suki Set (small)', emoji: '🫕', calories: 400, protein: 30, carbs: 35, fat: 14 },
      { name: 'MK Suki Set (large)', emoji: '🫕', calories: 650, protein: 48, carbs: 55, fat: 22 },
      { name: 'MK Fried Wonton', emoji: '🥟', calories: 280, protein: 10, carbs: 30, fat: 14 },
      { name: 'MK Steamed Dumpling (4pc)', emoji: '🥟', calories: 200, protein: 12, carbs: 22, fat: 6 },
      { name: 'MK Crispy Pork Roll', emoji: '🌯', calories: 240, protein: 8, carbs: 20, fat: 14 },
      { name: 'MK Boiled Egg Tofu', emoji: '🧊', calories: 80, protein: 8, carbs: 2, fat: 4 },
      { name: 'MK Glass Noodle', emoji: '🍜', calories: 160, protein: 1, carbs: 40, fat: 0 },
      { name: 'MK Seafood Platter', emoji: '🦐', calories: 300, protein: 35, carbs: 10, fat: 14 },
      { name: 'MK Sukiyaki Sauce (1 cup)', emoji: '🥣', calories: 60, protein: 2, carbs: 12, fat: 0 },
    ],
  },
  {
    label: 'Bonchon & Korean',
    emoji: '🍗',
    items: [
      { name: 'Bonchon Soy Garlic Wings (6pc)', emoji: '🍗', calories: 540, protein: 32, carbs: 28, fat: 32 },
      { name: 'Bonchon Spicy Wings (6pc)', emoji: '🍗', calories: 560, protein: 32, carbs: 30, fat: 34 },
      { name: 'Bonchon Strips (4pc)', emoji: '🍗', calories: 400, protein: 24, carbs: 22, fat: 24 },
      { name: 'Bonchon Bibimbap', emoji: '🍚', calories: 550, protein: 22, carbs: 65, fat: 20 },
      { name: 'Bonchon Japchae', emoji: '🍜', calories: 380, protein: 10, carbs: 52, fat: 14 },
      { name: 'Bonchon Tteokbokki', emoji: '🍡', calories: 350, protein: 8, carbs: 60, fat: 8 },
      { name: 'Bonchon Kimchi Fried Rice', emoji: '🍚', calories: 480, protein: 14, carbs: 62, fat: 18 },
    ],
  },
  {
    label: 'Starbucks',
    emoji: '☕',
    items: [
      { name: 'SB Caffe Latte (Grande)', emoji: '☕', calories: 190, protein: 10, carbs: 18, fat: 7 },
      { name: 'SB Cappuccino (Grande)', emoji: '☕', calories: 140, protein: 8, carbs: 14, fat: 5 },
      { name: 'SB Caramel Macchiato (Grande)', emoji: '☕', calories: 250, protein: 10, carbs: 34, fat: 7 },
      { name: 'SB Mocha Frappuccino (Grande)', emoji: '🥤', calories: 370, protein: 6, carbs: 62, fat: 11 },
      { name: 'SB Caramel Frappuccino (Grande)', emoji: '🥤', calories: 380, protein: 5, carbs: 60, fat: 14 },
      { name: 'SB Matcha Green Tea Latte (Grande)', emoji: '🍵', calories: 240, protein: 8, carbs: 34, fat: 7 },
      { name: 'SB Americano (Grande)', emoji: '☕', calories: 15, protein: 1, carbs: 2, fat: 0 },
      { name: 'SB Chocolate Croissant', emoji: '🥐', calories: 340, protein: 6, carbs: 38, fat: 18 },
      { name: 'SB Butter Croissant', emoji: '🥐', calories: 280, protein: 5, carbs: 30, fat: 16 },
      { name: 'SB Banana Cake', emoji: '🍰', calories: 390, protein: 5, carbs: 52, fat: 18 },
    ],
  },
  {
    label: 'Subway',
    emoji: '🥖',
    items: [
      { name: 'Subway Tuna 6"', emoji: '🥖', calories: 480, protein: 20, carbs: 44, fat: 24 },
      { name: 'Subway Chicken Teriyaki 6"', emoji: '🥖', calories: 370, protein: 26, carbs: 46, fat: 6 },
      { name: 'Subway Italian BMT 6"', emoji: '🥖', calories: 410, protein: 18, carbs: 44, fat: 18 },
      { name: 'Subway Turkey Breast 6"', emoji: '🥖', calories: 280, protein: 18, carbs: 42, fat: 4 },
      { name: 'Subway Veggie Delite 6"', emoji: '🥖', calories: 230, protein: 8, carbs: 42, fat: 3 },
      { name: 'Subway Steak & Cheese 6"', emoji: '🥖', calories: 380, protein: 24, carbs: 44, fat: 12 },
      { name: 'Subway Cookie (1pc)', emoji: '🍪', calories: 200, protein: 2, carbs: 28, fat: 10 },
    ],
  },
  {
    label: 'CoCo Ichibanya',
    emoji: '🍛',
    items: [
      { name: 'CoCo Curry Pork Katsu', emoji: '🍛', calories: 820, protein: 28, carbs: 100, fat: 32 },
      { name: 'CoCo Curry Chicken Katsu', emoji: '🍛', calories: 780, protein: 30, carbs: 98, fat: 28 },
      { name: 'CoCo Curry Shrimp Fry', emoji: '🍛', calories: 750, protein: 22, carbs: 96, fat: 26 },
      { name: 'CoCo Curry Beef', emoji: '🍛', calories: 700, protein: 24, carbs: 92, fat: 24 },
      { name: 'CoCo Curry Vegetable', emoji: '🍛', calories: 600, protein: 12, carbs: 90, fat: 18 },
      { name: 'CoCo Curry Omelette', emoji: '🍛', calories: 720, protein: 22, carbs: 88, fat: 28 },
      { name: 'CoCo Curry (rice -50%)', emoji: '🍛', calories: -150, protein: -2, carbs: -35, fat: 0 },
    ],
  },
  {
    label: 'Yoshinoya',
    emoji: '🥩',
    items: [
      { name: 'Yoshinoya Beef Gyudon (M)', emoji: '🥩', calories: 580, protein: 22, carbs: 72, fat: 20 },
      { name: 'Yoshinoya Beef Gyudon (L)', emoji: '🥩', calories: 780, protein: 30, carbs: 96, fat: 28 },
      { name: 'Yoshinoya Chicken Teriyaki Don', emoji: '🍗', calories: 550, protein: 26, carbs: 68, fat: 16 },
      { name: 'Yoshinoya Salmon Don', emoji: '🐟', calories: 520, protein: 24, carbs: 64, fat: 16 },
      { name: 'Yoshinoya Pork Katsu Don', emoji: '🍚', calories: 650, protein: 24, carbs: 78, fat: 24 },
      { name: 'Yoshinoya Miso Soup', emoji: '🍲', calories: 40, protein: 3, carbs: 4, fat: 1 },
      { name: 'Yoshinoya Edamame', emoji: '🫛', calories: 120, protein: 10, carbs: 8, fat: 5 },
    ],
  },
  {
    label: 'Sizzler',
    emoji: '🥩',
    items: [
      { name: 'Sizzler Sirloin Steak 200g', emoji: '🥩', calories: 480, protein: 42, carbs: 0, fat: 34 },
      { name: 'Sizzler Chicken Steak', emoji: '🍗', calories: 380, protein: 36, carbs: 4, fat: 24 },
      { name: 'Sizzler Salmon Steak', emoji: '🐟', calories: 420, protein: 38, carbs: 2, fat: 28 },
      { name: 'Sizzler Salad Bar (1 plate)', emoji: '🥗', calories: 250, protein: 8, carbs: 20, fat: 16 },
      { name: 'Sizzler Baked Potato', emoji: '🥔', calories: 300, protein: 6, carbs: 52, fat: 8 },
      { name: 'Sizzler Toast (2pc)', emoji: '🍞', calories: 200, protein: 4, carbs: 28, fat: 8 },
      { name: 'Sizzler Soup (1 bowl)', emoji: '🍲', calories: 180, protein: 6, carbs: 18, fat: 8 },
    ],
  },
  {
    label: 'Chester\'s & Texas Chicken',
    emoji: '🍗',
    items: [
      { name: 'Chester\'s Grilled Chicken (1pc)', emoji: '🍗', calories: 280, protein: 28, carbs: 6, fat: 16 },
      { name: 'Chester\'s Fried Chicken (1pc)', emoji: '🍗', calories: 350, protein: 24, carbs: 14, fat: 22 },
      { name: 'Chester\'s Chicken Rice', emoji: '🍚', calories: 520, protein: 28, carbs: 58, fat: 16 },
      { name: 'Chester\'s Chicken Wrap', emoji: '🌯', calories: 420, protein: 20, carbs: 40, fat: 20 },
      { name: 'Texas Chicken Original (1pc)', emoji: '🍗', calories: 360, protein: 24, carbs: 14, fat: 24 },
      { name: 'Texas Chicken Spicy (1pc)', emoji: '🍗', calories: 370, protein: 24, carbs: 16, fat: 24 },
      { name: 'Texas Chicken Burger', emoji: '🍔', calories: 480, protein: 22, carbs: 44, fat: 24 },
      { name: 'Texas Honey Biscuit', emoji: '🧈', calories: 280, protein: 4, carbs: 36, fat: 14 },
    ],
  },
  {
    label: 'Bar-B-Q Plaza',
    emoji: '🥘',
    items: [
      { name: 'BBQ Plaza Pork Set', emoji: '🥩', calories: 450, protein: 30, carbs: 20, fat: 28 },
      { name: 'BBQ Plaza Beef Set', emoji: '🥩', calories: 480, protein: 32, carbs: 18, fat: 30 },
      { name: 'BBQ Plaza Seafood Set', emoji: '🦐', calories: 350, protein: 28, carbs: 18, fat: 18 },
      { name: 'BBQ Plaza Mixed Set', emoji: '🥘', calories: 500, protein: 34, carbs: 22, fat: 28 },
      { name: 'BBQ Plaza Sauce (1 cup)', emoji: '🥣', calories: 80, protein: 2, carbs: 14, fat: 2 },
      { name: 'BBQ Plaza Vermicelli Soup', emoji: '🍲', calories: 180, protein: 8, carbs: 28, fat: 4 },
      { name: 'BBQ Plaza Rice (1 portion)', emoji: '🍚', calories: 250, protein: 5, carbs: 55, fat: 1 },
    ],
  },
  {
    label: 'After You & Dessert Cafe',
    emoji: '🍰',
    items: [
      { name: 'After You Shibuya Toast', emoji: '🍞', calories: 680, protein: 10, carbs: 82, fat: 34 },
      { name: 'After You Kakigori (shaved ice)', emoji: '🍧', calories: 450, protein: 6, carbs: 70, fat: 16 },
      { name: 'After You Chocolate Toast', emoji: '🍫', calories: 720, protein: 12, carbs: 88, fat: 36 },
      { name: 'After You Matcha Lava', emoji: '🍵', calories: 520, protein: 8, carbs: 64, fat: 26 },
      { name: 'After You Croffle', emoji: '🧇', calories: 380, protein: 6, carbs: 46, fat: 20 },
    ],
  },
];
