export interface FoodPreset {
  name: string;
  /** Thai display name, shown in the adult (Thai) mode */
  nameTh?: string;
  emoji: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  /** mg, approximate; absent where unknown */
  sodium?: number;
  /** grams of sugar, approximate; absent where unknown */
  sugar?: number;
}

export interface PresetCategory {
  label: string;
  /** Thai category name, shown in the adult (Thai) mode */
  labelTh?: string;
  emoji: string;
  items: FoodPreset[];
}

// Approximate values per typical serving/plate
export const FOOD_PRESET_CATEGORIES: PresetCategory[] = [
  {
    label: 'Rice & Noodles',
    labelTh: 'ข้าวและเส้น',
    emoji: '🍚',
    items: [
      { name: 'Pad Thai', nameTh: 'ผัดไทย', emoji: '🍜', calories: 450, protein: 18, carbs: 55, fat: 16, sodium: 1200, sugar: 12 },
      { name: 'Pad See Ew', nameTh: 'ผัดซีอิ๊ว', emoji: '🍜', calories: 480, protein: 20, carbs: 58, fat: 16, sodium: 1300, sugar: 8 },
      { name: 'Pad Kra Pao + Rice', nameTh: 'ข้าวผัดกะเพรา', emoji: '🍚', calories: 550, protein: 28, carbs: 60, fat: 18, sodium: 1300, sugar: 4 },
      { name: 'Khao Pad (Fried Rice)', nameTh: 'ข้าวผัด', emoji: '🍚', calories: 500, protein: 16, carbs: 62, fat: 18, sodium: 1100, sugar: 3 },
      { name: 'Khao Man Gai', nameTh: 'ข้าวมันไก่', emoji: '🍗', calories: 580, protein: 32, carbs: 55, fat: 22, sodium: 1400, sugar: 2 },
      { name: 'Khao Moo Daeng', nameTh: 'ข้าวหมูแดง', emoji: '🍚', calories: 520, protein: 30, carbs: 58, fat: 14, sodium: 1300, sugar: 10 },
      { name: 'Boat Noodles', nameTh: 'ก๋วยเตี๋ยวเรือ', emoji: '🍜', calories: 350, protein: 22, carbs: 40, fat: 10, sodium: 1500, sugar: 4 },
      { name: 'Pad Woon Sen', nameTh: 'ผัดวุ้นเส้น', emoji: '🍜', calories: 380, protein: 15, carbs: 48, fat: 12, sodium: 1100, sugar: 5 },
      { name: 'Rad Na', nameTh: 'ราดหน้า', emoji: '🍜', calories: 460, protein: 22, carbs: 52, fat: 16, sodium: 1400, sugar: 6 },
      { name: 'Kuay Teaw (Noodle Soup)', nameTh: 'ก๋วยเตี๋ยวน้ำ', emoji: '🍜', calories: 380, protein: 24, carbs: 42, fat: 10, sodium: 1600, sugar: 4 },
    ],
  },
  {
    label: 'Curries & Soups',
    labelTh: 'แกงและต้ม',
    emoji: '🍛',
    items: [
      { name: 'Green Curry + Rice', nameTh: 'ข้าวแกงเขียวหวาน', emoji: '🟢', calories: 550, protein: 24, carbs: 55, fat: 24, sodium: 1200, sugar: 8 },
      { name: 'Red Curry + Rice', nameTh: 'ข้าวแกงเผ็ด', emoji: '🔴', calories: 530, protein: 22, carbs: 54, fat: 22, sodium: 1200, sugar: 7 },
      { name: 'Massaman Curry + Rice', nameTh: 'ข้าวแกงมัสมั่น', emoji: '🍛', calories: 620, protein: 26, carbs: 58, fat: 28, sodium: 1100, sugar: 12 },
      { name: 'Panang Curry + Rice', nameTh: 'ข้าวพะแนง', emoji: '🍛', calories: 560, protein: 25, carbs: 52, fat: 26, sodium: 1100, sugar: 9 },
      { name: 'Tom Yum Goong', nameTh: 'ต้มยำกุ้ง', emoji: '🍲', calories: 200, protein: 20, carbs: 12, fat: 8, sodium: 1500, sugar: 4 },
      { name: 'Tom Kha Gai', nameTh: 'ต้มข่าไก่', emoji: '🍲', calories: 300, protein: 18, carbs: 10, fat: 22, sodium: 1100, sugar: 4 },
      { name: 'Gaeng Jued (Clear Soup)', nameTh: 'แกงจืด', emoji: '🍲', calories: 150, protein: 12, carbs: 10, fat: 6, sodium: 900, sugar: 2 },
    ],
  },
  {
    label: 'Stir-fry & Sides',
    labelTh: 'ผัดและกับข้าว',
    emoji: '🥘',
    items: [
      { name: 'Gai Pad Med Mamuang', nameTh: 'ไก่ผัดเม็ดมะม่วง', emoji: '🥜', calories: 420, protein: 28, carbs: 20, fat: 26, sodium: 1000, sugar: 8 },
      { name: 'Larb Moo', nameTh: 'ลาบหมู', emoji: '🥗', calories: 280, protein: 26, carbs: 8, fat: 16, sodium: 900, sugar: 3 },
      { name: 'Som Tam', nameTh: 'ส้มตำ', emoji: '🥗', calories: 120, protein: 4, carbs: 18, fat: 4, sodium: 1100, sugar: 10 },
      { name: 'Kai Jeow (Thai Omelette)', nameTh: 'ไข่เจียว', emoji: '🍳', calories: 300, protein: 16, carbs: 4, fat: 24, sodium: 600, sugar: 1 },
      { name: 'Moo Ping (Grilled Pork)', nameTh: 'หมูปิ้ง', emoji: '🍢', calories: 250, protein: 22, carbs: 10, fat: 14, sodium: 500, sugar: 6 },
      { name: 'Gai Yang (Grilled Chicken)', nameTh: 'ไก่ย่าง', emoji: '🍗', calories: 320, protein: 34, carbs: 6, fat: 18, sodium: 700, sugar: 3 },
      { name: 'Steamed Rice (1 plate)', nameTh: 'ข้าวสวย (1 จาน)', emoji: '🍚', calories: 250, protein: 5, carbs: 55, fat: 1, sodium: 5, sugar: 0 },
      { name: 'Sticky Rice (1 portion)', nameTh: 'ข้าวเหนียว (1 ห่อ)', emoji: '🍚', calories: 200, protein: 4, carbs: 44, fat: 0, sodium: 5, sugar: 0 },
    ],
  },
  {
    label: 'Drinks & Desserts',
    labelTh: 'เครื่องดื่มและของหวาน',
    emoji: '🧋',
    items: [
      { name: 'Thai Iced Tea', nameTh: 'ชาเย็น', emoji: '🧋', calories: 200, protein: 2, carbs: 38, fat: 5, sodium: 60, sugar: 32 },
      { name: 'Thai Iced Coffee', nameTh: 'กาแฟเย็น', emoji: '☕', calories: 180, protein: 2, carbs: 32, fat: 5, sodium: 60, sugar: 28 },
      { name: 'Mango Sticky Rice', nameTh: 'ข้าวเหนียวมะม่วง', emoji: '🥭', calories: 400, protein: 5, carbs: 72, fat: 12, sodium: 150, sugar: 40 },
      { name: 'Roti + Condensed Milk', nameTh: 'โรตีนมข้น', emoji: '🫓', calories: 350, protein: 6, carbs: 48, fat: 16, sodium: 300, sugar: 30 },
      { name: 'Kanom Buang (Crispy Crepe)', nameTh: 'ขนมเบื้อง', emoji: '🥞', calories: 150, protein: 3, carbs: 22, fat: 6, sodium: 120, sugar: 14 },
    ],
  },
  {
    label: '7-Eleven Meals',
    labelTh: 'เซเว่น อาหาร',
    emoji: '🏪',
    items: [
      { name: '7-11 Toasted Ham & Cheese', nameTh: 'เซเว่น แซนด์วิชแฮมชีส', emoji: '🥪', calories: 280, protein: 14, carbs: 28, fat: 12, sodium: 700, sugar: 4 },
      { name: '7-11 Toasted Tuna', nameTh: 'เซเว่น แซนด์วิชทูน่า', emoji: '🥪', calories: 300, protein: 16, carbs: 30, fat: 12, sodium: 650, sugar: 4 },
      { name: '7-11 Toasted Crab Stick', nameTh: 'เซเว่น แซนด์วิชปูอัด', emoji: '🥪', calories: 260, protein: 10, carbs: 30, fat: 10, sodium: 700, sugar: 5 },
      { name: '7-11 Croissant Ham Cheese', nameTh: 'เซเว่น ครัวซองแฮมชีส', emoji: '🥐', calories: 320, protein: 12, carbs: 28, fat: 18, sodium: 650, sugar: 5 },
      { name: '7-11 Chicken Teriyaki Bento', nameTh: 'เซเว่น ข้าวไก่เทอริยากิ', emoji: '🍱', calories: 520, protein: 24, carbs: 68, fat: 14, sodium: 1100, sugar: 12 },
      { name: '7-11 Pad Kra Pao Bento', nameTh: 'เซเว่น ข้าวกะเพรา', emoji: '🍱', calories: 550, protein: 22, carbs: 65, fat: 18, sodium: 1200, sugar: 5 },
      { name: '7-11 Pork Tonkatsu Bento', nameTh: 'เซเว่น ข้าวหมูทงคัตสึ', emoji: '🍱', calories: 580, protein: 20, carbs: 70, fat: 20, sodium: 1100, sugar: 8 },
      { name: '7-11 Green Curry Rice Bento', nameTh: 'เซเว่น ข้าวแกงเขียวหวาน', emoji: '🍱', calories: 500, protein: 18, carbs: 62, fat: 16, sodium: 1100, sugar: 7 },
      { name: '7-11 Omurice Bento', nameTh: 'เซเว่น ข้าวไข่ข้น', emoji: '🍱', calories: 480, protein: 16, carbs: 60, fat: 16, sodium: 1000, sugar: 8 },
      { name: '7-11 Salmon Onigiri', nameTh: 'เซเว่น โอนิกิริแซลมอน', emoji: '🍙', calories: 180, protein: 8, carbs: 30, fat: 3, sodium: 400, sugar: 2 },
      { name: '7-11 Tuna Mayo Onigiri', nameTh: 'เซเว่น โอนิกิริทูน่ามายองเนส', emoji: '🍙', calories: 200, protein: 8, carbs: 28, fat: 6, sodium: 420, sugar: 2 },
      { name: '7-11 Chicken Onigiri', nameTh: 'เซเว่น โอนิกิริไก่', emoji: '🍙', calories: 190, protein: 9, carbs: 28, fat: 4, sodium: 450, sugar: 3 },
      { name: '7-11 Shrimp Tempura Onigiri', nameTh: 'เซเว่น โอนิกิริกุ้งเทมปุระ', emoji: '🍙', calories: 195, protein: 7, carbs: 32, fat: 4, sodium: 430, sugar: 3 },
      { name: '7-11 Salapao Moo (Pork Bun)', nameTh: 'เซเว่น ซาลาเปาหมู', emoji: '🫓', calories: 220, protein: 10, carbs: 30, fat: 6, sodium: 450, sugar: 8 },
      { name: '7-11 Salapao Sai Kai Kem', nameTh: 'เซเว่น ซาลาเปาไส้ไข่เค็ม', emoji: '🫓', calories: 250, protein: 8, carbs: 32, fat: 10, sodium: 500, sugar: 9 },
      { name: '7-11 Salapao Custard', nameTh: 'เซเว่น ซาลาเปาคัสตาร์ด', emoji: '🫓', calories: 230, protein: 5, carbs: 36, fat: 8, sodium: 200, sugar: 16 },
      { name: '7-11 Hot Dog (regular)', nameTh: 'เซเว่น ฮอทดอก', emoji: '🌭', calories: 280, protein: 10, carbs: 28, fat: 14, sodium: 800, sugar: 6 },
      { name: '7-11 Big Bite Sausage', nameTh: 'เซเว่น ไส้กรอกบิ๊กไบท์', emoji: '🌭', calories: 350, protein: 14, carbs: 30, fat: 18, sodium: 900, sugar: 5 },
      { name: '7-11 Fried Chicken Wing (2pc)', nameTh: 'เซเว่น ปีกไก่ทอด (2 ชิ้น)', emoji: '🍗', calories: 320, protein: 20, carbs: 16, fat: 20, sodium: 700, sugar: 2 },
      { name: '7-11 Mama Cup Noodle', nameTh: 'เซเว่น มาม่าคัพ', emoji: '🍜', calories: 300, protein: 7, carbs: 40, fat: 12, sodium: 1500, sugar: 3 },
    ],
  },
  {
    label: '7-Eleven Drinks & Snacks',
    labelTh: 'เซเว่น เครื่องดื่มและขนม',
    emoji: '🥤',
    items: [
      { name: '7-11 Iced Coffee (All Cafe)', nameTh: 'เซเว่น กาแฟเย็น (ออลคาเฟ่)', emoji: '☕', calories: 120, protein: 3, carbs: 18, fat: 4, sugar: 16 },
      { name: '7-11 Latte (All Cafe)', nameTh: 'เซเว่น ลาเต้ (ออลคาเฟ่)', emoji: '☕', calories: 150, protein: 5, carbs: 20, fat: 5, sugar: 18 },
      { name: '7-11 Mocha (All Cafe)', nameTh: 'เซเว่น มอคค่า (ออลคาเฟ่)', emoji: '☕', calories: 200, protein: 5, carbs: 30, fat: 6, sugar: 26 },
      { name: '7-11 Matcha Latte (All Cafe)', nameTh: 'เซเว่น มัทฉะลาเต้ (ออลคาเฟ่)', emoji: '🍵', calories: 180, protein: 4, carbs: 28, fat: 5, sugar: 24 },
      { name: '7-11 Cocoa (All Cafe)', nameTh: 'เซเว่น โกโก้ (ออลคาเฟ่)', emoji: '🍫', calories: 210, protein: 5, carbs: 32, fat: 7, sugar: 28 },
      { name: '7-11 Slurpee (medium)', nameTh: 'เซเว่น สเลอปี้ (กลาง)', emoji: '🥤', calories: 180, protein: 0, carbs: 46, fat: 0, sugar: 44 },
      { name: '7-11 Banana Cake', nameTh: 'เซเว่น เค้กกล้วยหอม', emoji: '🍰', calories: 280, protein: 4, carbs: 40, fat: 12, sugar: 24 },
      { name: '7-11 Choco Lava', nameTh: 'เซเว่น ช็อกโกลาวา', emoji: '🍫', calories: 300, protein: 5, carbs: 42, fat: 14, sugar: 28 },
      { name: '7-11 Egg Custard Bread', nameTh: 'เซเว่น ขนมปังสังขยา', emoji: '🍞', calories: 260, protein: 6, carbs: 36, fat: 10, sugar: 18 },
      { name: '7-11 Butter Toast (2pc)', nameTh: 'เซเว่น ขนมปังปิ้งเนย (2 ชิ้น)', emoji: '🍞', calories: 220, protein: 4, carbs: 30, fat: 10, sugar: 10 },
      { name: '7-11 Yogurt Drink', nameTh: 'เซเว่น นมเปรี้ยว', emoji: '🥛', calories: 140, protein: 4, carbs: 26, fat: 2, sugar: 22 },
      { name: '7-11 Protein Milk', nameTh: 'เซเว่น นมโปรตีน', emoji: '🥛', calories: 160, protein: 20, carbs: 14, fat: 2, sugar: 10 },
    ],
  },
  {
    label: 'McDonald\'s',
    labelTh: 'แมคโดนัลด์',
    emoji: '🍔',
    items: [
      { name: 'McD Big Mac', emoji: '🍔', calories: 550, protein: 25, carbs: 45, fat: 30 },
      { name: 'McD McChicken', emoji: '🍔', calories: 400, protein: 14, carbs: 40, fat: 22 },
      { name: 'McD Quarter Pounder', emoji: '🍔', calories: 520, protein: 30, carbs: 40, fat: 26 },
      { name: 'McD Double Cheeseburger', emoji: '🍔', calories: 450, protein: 25, carbs: 34, fat: 24 },
      { name: 'McD Samurai Pork Burger', nameTh: 'แมค ซามูไรพอร์คเบอร์เกอร์', emoji: '🍔', calories: 480, protein: 22, carbs: 42, fat: 22 },
      { name: 'McD Spicy Chicken', emoji: '🍔', calories: 450, protein: 18, carbs: 44, fat: 22 },
      { name: 'McD Chicken McNuggets (6pc)', nameTh: 'แมค นักเก็ตไก่ (6 ชิ้น)', emoji: '🍗', calories: 280, protein: 14, carbs: 18, fat: 16 },
      { name: 'McD Chicken McNuggets (9pc)', nameTh: 'แมค นักเก็ตไก่ (9 ชิ้น)', emoji: '🍗', calories: 420, protein: 21, carbs: 27, fat: 24 },
      { name: 'McD French Fries (M)', nameTh: 'แมค เฟรนช์ฟรายส์ (กลาง)', emoji: '🍟', calories: 340, protein: 4, carbs: 44, fat: 16 },
      { name: 'McD French Fries (L)', nameTh: 'แมค เฟรนช์ฟรายส์ (ใหญ่)', emoji: '🍟', calories: 490, protein: 6, carbs: 64, fat: 23 },
      { name: 'McD Egg McMuffin', emoji: '🍳', calories: 300, protein: 17, carbs: 26, fat: 13 },
      { name: 'McD Pork Sausage McMuffin', emoji: '🍳', calories: 400, protein: 16, carbs: 28, fat: 24 },
      { name: 'McD McFlurry Oreo', emoji: '🍦', calories: 340, protein: 8, carbs: 52, fat: 12, sugar: 45 },
      { name: 'McD Cone', nameTh: 'แมค ไอศกรีมโคน', emoji: '🍦', calories: 150, protein: 4, carbs: 24, fat: 4, sugar: 16 },
      { name: 'McD Apple Pie', nameTh: 'แมค พายแอปเปิ้ล', emoji: '🥧', calories: 250, protein: 2, carbs: 32, fat: 14, sugar: 13 },
    ],
  },
  {
    label: 'KFC',
    labelTh: 'เคเอฟซี',
    emoji: '🍗',
    items: [
      { name: 'KFC Original Chicken (1pc)', nameTh: 'เคเอฟซี ไก่ทอดสูตรดั้งเดิม (1 ชิ้น)', emoji: '🍗', calories: 320, protein: 22, carbs: 12, fat: 22 },
      { name: 'KFC Hot & Crispy (1pc)', nameTh: 'เคเอฟซี ไก่ทอดวิงซ์แซ่บ (1 ชิ้น)', emoji: '🍗', calories: 350, protein: 20, carbs: 16, fat: 24 },
      { name: 'KFC Chicken Strips (3pc)', nameTh: 'เคเอฟซี ไก่สตริปส์ (3 ชิ้น)', emoji: '🍗', calories: 380, protein: 26, carbs: 20, fat: 22 },
      { name: 'KFC Zinger Burger', emoji: '🍔', calories: 480, protein: 22, carbs: 42, fat: 24 },
      { name: 'KFC Colonel Burger', emoji: '🍔', calories: 450, protein: 20, carbs: 40, fat: 22 },
      { name: 'KFC Twister Wrap', emoji: '🌯', calories: 420, protein: 18, carbs: 38, fat: 22 },
      { name: 'KFC Coleslaw', nameTh: 'เคเอฟซี โคลสลอว์', emoji: '🥗', calories: 150, protein: 1, carbs: 14, fat: 10 },
      { name: 'KFC Mashed Potato + Gravy', nameTh: 'เคเอฟซี มันบดเกรวี่', emoji: '🥔', calories: 130, protein: 2, carbs: 18, fat: 5 },
      { name: 'KFC Corn on the Cob', nameTh: 'เคเอฟซี ข้าวโพด', emoji: '🌽', calories: 140, protein: 4, carbs: 26, fat: 3 },
      { name: 'KFC Rice (1 serving)', nameTh: 'เคเอฟซี ข้าวสวย', emoji: '🍚', calories: 260, protein: 5, carbs: 56, fat: 1 },
      { name: 'KFC Egg Tart', nameTh: 'เคเอฟซี ทาร์ตไข่', emoji: '🥧', calories: 200, protein: 4, carbs: 22, fat: 10, sugar: 10 },
    ],
  },
  {
    label: 'Burger King',
    labelTh: 'เบอร์เกอร์คิง',
    emoji: '🍔',
    items: [
      { name: 'BK Whopper', emoji: '🍔', calories: 660, protein: 28, carbs: 49, fat: 40 },
      { name: 'BK Whopper Jr', emoji: '🍔', calories: 310, protein: 13, carbs: 27, fat: 18 },
      { name: 'BK Double Cheeseburger', emoji: '🍔', calories: 380, protein: 22, carbs: 28, fat: 20 },
      { name: 'BK Chicken Royale', emoji: '🍔', calories: 530, protein: 22, carbs: 48, fat: 28 },
      { name: 'BK Fish Burger', nameTh: 'เบอร์เกอร์คิง เบอร์เกอร์ปลา', emoji: '🐟', calories: 400, protein: 16, carbs: 40, fat: 18 },
      { name: 'BK Onion Rings (M)', nameTh: 'เบอร์เกอร์คิง หัวหอมทอด (กลาง)', emoji: '🧅', calories: 320, protein: 4, carbs: 40, fat: 16 },
      { name: 'BK French Fries (M)', nameTh: 'เบอร์เกอร์คิง เฟรนช์ฟรายส์ (กลาง)', emoji: '🍟', calories: 340, protein: 4, carbs: 44, fat: 16 },
      { name: 'BK Chicken Nuggets (6pc)', nameTh: 'เบอร์เกอร์คิง นักเก็ตไก่ (6 ชิ้น)', emoji: '🍗', calories: 260, protein: 12, carbs: 16, fat: 16 },
    ],
  },
  {
    label: 'Pizza Company',
    labelTh: 'พิซซ่าคอมปะนี',
    emoji: '🍕',
    items: [
      { name: 'Pizza Co. Super Supreme (1 slice)', emoji: '🍕', calories: 280, protein: 12, carbs: 30, fat: 12 },
      { name: 'Pizza Co. Hawaian (1 slice)', emoji: '🍕', calories: 240, protein: 10, carbs: 30, fat: 8 },
      { name: 'Pizza Co. Seafood Deluxe (1 slice)', emoji: '🍕', calories: 260, protein: 12, carbs: 28, fat: 10 },
      { name: 'Pizza Co. Pepperoni (1 slice)', emoji: '🍕', calories: 270, protein: 12, carbs: 28, fat: 12 },
      { name: 'Pizza Co. Chicken Wings (6pc)', nameTh: 'พิซซ่าคอมปะนี ปีกไก่ (6 ชิ้น)', emoji: '🍗', calories: 420, protein: 28, carbs: 16, fat: 28 },
      { name: 'Pizza Co. Garlic Bread (2pc)', nameTh: 'พิซซ่าคอมปะนี ขนมปังกระเทียม (2 ชิ้น)', emoji: '🍞', calories: 200, protein: 4, carbs: 28, fat: 8 },
      { name: 'Pizza Co. Spaghetti Carbonara', nameTh: 'พิซซ่าคอมปะนี สปาเก็ตตี้คาโบนาร่า', emoji: '🍝', calories: 520, protein: 18, carbs: 58, fat: 22 },
      { name: 'Pizza Co. Spaghetti Bolognese', nameTh: 'พิซซ่าคอมปะนี สปาเก็ตตี้โบโลเนส', emoji: '🍝', calories: 480, protein: 20, carbs: 56, fat: 18 },
    ],
  },
  {
    label: 'MK Restaurant',
    labelTh: 'เอ็มเค',
    emoji: '🫕',
    items: [
      { name: 'MK Suki Set (small)', nameTh: 'เอ็มเค ชุดสุกี้ (เล็ก)', emoji: '🫕', calories: 400, protein: 30, carbs: 35, fat: 14 },
      { name: 'MK Suki Set (large)', nameTh: 'เอ็มเค ชุดสุกี้ (ใหญ่)', emoji: '🫕', calories: 650, protein: 48, carbs: 55, fat: 22 },
      { name: 'MK Fried Wonton', nameTh: 'เอ็มเค เกี๊ยวทอด', emoji: '🥟', calories: 280, protein: 10, carbs: 30, fat: 14 },
      { name: 'MK Steamed Dumpling (4pc)', nameTh: 'เอ็มเค ติ่มซำ (4 ชิ้น)', emoji: '🥟', calories: 200, protein: 12, carbs: 22, fat: 6 },
      { name: 'MK Crispy Pork Roll', nameTh: 'เอ็มเค เป็ดย่าง/หมูกรอบม้วน', emoji: '🌯', calories: 240, protein: 8, carbs: 20, fat: 14 },
      { name: 'MK Boiled Egg Tofu', nameTh: 'เอ็มเค เต้าหู้ไข่', emoji: '🧊', calories: 80, protein: 8, carbs: 2, fat: 4 },
      { name: 'MK Glass Noodle', nameTh: 'เอ็มเค วุ้นเส้น', emoji: '🍜', calories: 160, protein: 1, carbs: 40, fat: 0 },
      { name: 'MK Seafood Platter', nameTh: 'เอ็มเค ชุดทะเล', emoji: '🦐', calories: 300, protein: 35, carbs: 10, fat: 14 },
      { name: 'MK Sukiyaki Sauce (1 cup)', nameTh: 'เอ็มเค น้ำจิ้มสุกี้ (1 ถ้วย)', emoji: '🥣', calories: 60, protein: 2, carbs: 12, fat: 0 },
    ],
  },
  {
    label: 'Bonchon & Korean',
    labelTh: 'บอนชอนและอาหารเกาหลี',
    emoji: '🍗',
    items: [
      { name: 'Bonchon Soy Garlic Wings (6pc)', nameTh: 'บอนชอน ปีกไก่ซอยการ์ลิค (6 ชิ้น)', emoji: '🍗', calories: 540, protein: 32, carbs: 28, fat: 32 },
      { name: 'Bonchon Spicy Wings (6pc)', nameTh: 'บอนชอน ปีกไก่เผ็ด (6 ชิ้น)', emoji: '🍗', calories: 560, protein: 32, carbs: 30, fat: 34 },
      { name: 'Bonchon Strips (4pc)', nameTh: 'บอนชอน ไก่สตริปส์ (4 ชิ้น)', emoji: '🍗', calories: 400, protein: 24, carbs: 22, fat: 24 },
      { name: 'Bonchon Bibimbap', nameTh: 'บอนชอน บิบิมบับ', emoji: '🍚', calories: 550, protein: 22, carbs: 65, fat: 20 },
      { name: 'Bonchon Japchae', nameTh: 'บอนชอน จับเช', emoji: '🍜', calories: 380, protein: 10, carbs: 52, fat: 14 },
      { name: 'Bonchon Tteokbokki', nameTh: 'บอนชอน ต็อกบกกี', emoji: '🍡', calories: 350, protein: 8, carbs: 60, fat: 8 },
      { name: 'Bonchon Kimchi Fried Rice', nameTh: 'บอนชอน ข้าวผัดกิมจิ', emoji: '🍚', calories: 480, protein: 14, carbs: 62, fat: 18 },
    ],
  },
  {
    label: 'Starbucks',
    labelTh: 'สตาร์บัคส์',
    emoji: '☕',
    items: [
      { name: 'SB Caffe Latte (Grande)', emoji: '☕', calories: 190, protein: 10, carbs: 18, fat: 7, sugar: 17 },
      { name: 'SB Cappuccino (Grande)', emoji: '☕', calories: 140, protein: 8, carbs: 14, fat: 5, sugar: 10 },
      { name: 'SB Caramel Macchiato (Grande)', emoji: '☕', calories: 250, protein: 10, carbs: 34, fat: 7, sugar: 33 },
      { name: 'SB Mocha Frappuccino (Grande)', emoji: '🥤', calories: 370, protein: 6, carbs: 62, fat: 11, sugar: 54 },
      { name: 'SB Caramel Frappuccino (Grande)', emoji: '🥤', calories: 380, protein: 5, carbs: 60, fat: 14, sugar: 55 },
      { name: 'SB Matcha Green Tea Latte (Grande)', emoji: '🍵', calories: 240, protein: 8, carbs: 34, fat: 7, sugar: 32 },
      { name: 'SB Americano (Grande)', emoji: '☕', calories: 15, protein: 1, carbs: 2, fat: 0, sugar: 0 },
      { name: 'SB Chocolate Croissant', nameTh: 'สตาร์บัคส์ ครัวซองช็อกโกแลต', emoji: '🥐', calories: 340, protein: 6, carbs: 38, fat: 18, sugar: 12 },
      { name: 'SB Butter Croissant', nameTh: 'สตาร์บัคส์ ครัวซองเนย', emoji: '🥐', calories: 280, protein: 5, carbs: 30, fat: 16, sugar: 6 },
      { name: 'SB Banana Cake', nameTh: 'สตาร์บัคส์ เค้กกล้วยหอม', emoji: '🍰', calories: 390, protein: 5, carbs: 52, fat: 18, sugar: 26 },
    ],
  },
  {
    label: 'Subway',
    labelTh: 'ซับเวย์',
    emoji: '🥖',
    items: [
      { name: 'Subway Tuna 6"', emoji: '🥖', calories: 480, protein: 20, carbs: 44, fat: 24 },
      { name: 'Subway Chicken Teriyaki 6"', emoji: '🥖', calories: 370, protein: 26, carbs: 46, fat: 6 },
      { name: 'Subway Italian BMT 6"', emoji: '🥖', calories: 410, protein: 18, carbs: 44, fat: 18 },
      { name: 'Subway Turkey Breast 6"', emoji: '🥖', calories: 280, protein: 18, carbs: 42, fat: 4 },
      { name: 'Subway Veggie Delite 6"', emoji: '🥖', calories: 230, protein: 8, carbs: 42, fat: 3 },
      { name: 'Subway Steak & Cheese 6"', emoji: '🥖', calories: 380, protein: 24, carbs: 44, fat: 12 },
      { name: 'Subway Cookie (1pc)', nameTh: 'ซับเวย์ คุกกี้ (1 ชิ้น)', emoji: '🍪', calories: 200, protein: 2, carbs: 28, fat: 10 },
    ],
  },
  {
    label: 'CoCo Ichibanya',
    labelTh: 'โคโค่ อิฉิบันยะ',
    emoji: '🍛',
    items: [
      { name: 'CoCo Curry Pork Katsu', nameTh: 'โคโค่ ข้าวแกงกะหรี่หมูทอด', emoji: '🍛', calories: 820, protein: 28, carbs: 100, fat: 32 },
      { name: 'CoCo Curry Chicken Katsu', nameTh: 'โคโค่ ข้าวแกงกะหรี่ไก่ทอด', emoji: '🍛', calories: 780, protein: 30, carbs: 98, fat: 28 },
      { name: 'CoCo Curry Shrimp Fry', nameTh: 'โคโค่ ข้าวแกงกะหรี่กุ้งทอด', emoji: '🍛', calories: 750, protein: 22, carbs: 96, fat: 26 },
      { name: 'CoCo Curry Beef', nameTh: 'โคโค่ ข้าวแกงกะหรี่เนื้อ', emoji: '🍛', calories: 700, protein: 24, carbs: 92, fat: 24 },
      { name: 'CoCo Curry Vegetable', nameTh: 'โคโค่ ข้าวแกงกะหรี่ผัก', emoji: '🍛', calories: 600, protein: 12, carbs: 90, fat: 18 },
      { name: 'CoCo Curry Omelette', nameTh: 'โคโค่ ข้าวแกงกะหรี่ไข่ข้น', emoji: '🍛', calories: 720, protein: 22, carbs: 88, fat: 28 },
      { name: 'CoCo Curry (rice -50%)', nameTh: 'โคโค่ ข้าวแกงกะหรี่ (ข้าวครึ่งเดียว)', emoji: '🍛', calories: -150, protein: -2, carbs: -35, fat: 0 },
    ],
  },
  {
    label: 'Yoshinoya',
    labelTh: 'โยชิโนยะ',
    emoji: '🥩',
    items: [
      { name: 'Yoshinoya Beef Gyudon (M)', nameTh: 'โยชิโนยะ ข้าวหน้าเนื้อ (กลาง)', emoji: '🥩', calories: 580, protein: 22, carbs: 72, fat: 20 },
      { name: 'Yoshinoya Beef Gyudon (L)', nameTh: 'โยชิโนยะ ข้าวหน้าเนื้อ (ใหญ่)', emoji: '🥩', calories: 780, protein: 30, carbs: 96, fat: 28 },
      { name: 'Yoshinoya Chicken Teriyaki Don', nameTh: 'โยชิโนยะ ข้าวหน้าไก่เทอริยากิ', emoji: '🍗', calories: 550, protein: 26, carbs: 68, fat: 16 },
      { name: 'Yoshinoya Salmon Don', nameTh: 'โยชิโนยะ ข้าวหน้าแซลมอน', emoji: '🐟', calories: 520, protein: 24, carbs: 64, fat: 16 },
      { name: 'Yoshinoya Pork Katsu Don', nameTh: 'โยชิโนยะ ข้าวหน้าหมูทอด', emoji: '🍚', calories: 650, protein: 24, carbs: 78, fat: 24 },
      { name: 'Yoshinoya Miso Soup', nameTh: 'โยชิโนยะ ซุปมิโสะ', emoji: '🍲', calories: 40, protein: 3, carbs: 4, fat: 1 },
      { name: 'Yoshinoya Edamame', nameTh: 'โยชิโนยะ ถั่วแระ', emoji: '🫛', calories: 120, protein: 10, carbs: 8, fat: 5 },
    ],
  },
  {
    label: 'Sizzler',
    labelTh: 'ซิซซ์เล่อร์',
    emoji: '🥩',
    items: [
      { name: 'Sizzler Sirloin Steak 200g', nameTh: 'ซิซซ์เล่อร์ สเต๊กเซอร์ลอยน์ 200 กรัม', emoji: '🥩', calories: 480, protein: 42, carbs: 0, fat: 34 },
      { name: 'Sizzler Chicken Steak', nameTh: 'ซิซซ์เล่อร์ สเต๊กไก่', emoji: '🍗', calories: 380, protein: 36, carbs: 4, fat: 24 },
      { name: 'Sizzler Salmon Steak', nameTh: 'ซิซซ์เล่อร์ สเต๊กแซลมอน', emoji: '🐟', calories: 420, protein: 38, carbs: 2, fat: 28 },
      { name: 'Sizzler Salad Bar (1 plate)', nameTh: 'ซิซซ์เล่อร์ สลัดบาร์ (1 จาน)', emoji: '🥗', calories: 250, protein: 8, carbs: 20, fat: 16 },
      { name: 'Sizzler Baked Potato', nameTh: 'ซิซซ์เล่อร์ มันอบ', emoji: '🥔', calories: 300, protein: 6, carbs: 52, fat: 8 },
      { name: 'Sizzler Toast (2pc)', nameTh: 'ซิซซ์เล่อร์ ขนมปังปิ้ง (2 ชิ้น)', emoji: '🍞', calories: 200, protein: 4, carbs: 28, fat: 8 },
      { name: 'Sizzler Soup (1 bowl)', nameTh: 'ซิซซ์เล่อร์ ซุป (1 ถ้วย)', emoji: '🍲', calories: 180, protein: 6, carbs: 18, fat: 8 },
    ],
  },
  {
    label: 'Chester\'s & Texas Chicken',
    labelTh: 'เชสเตอร์และเท็กซัสชิคเก้น',
    emoji: '🍗',
    items: [
      { name: 'Chester\'s Grilled Chicken (1pc)', emoji: '🍗', calories: 280, protein: 28, carbs: 6, fat: 16 },
      { name: 'Chester\'s Fried Chicken (1pc)', emoji: '🍗', calories: 350, protein: 24, carbs: 14, fat: 22 },
      { name: 'Chester\'s Chicken Rice', emoji: '🍚', calories: 520, protein: 28, carbs: 58, fat: 16 },
      { name: 'Chester\'s Chicken Wrap', emoji: '🌯', calories: 420, protein: 20, carbs: 40, fat: 20 },
      { name: 'Texas Chicken Original (1pc)', nameTh: 'เท็กซัสชิคเก้น ไก่ทอดดั้งเดิม (1 ชิ้น)', emoji: '🍗', calories: 360, protein: 24, carbs: 14, fat: 24 },
      { name: 'Texas Chicken Spicy (1pc)', nameTh: 'เท็กซัสชิคเก้น ไก่ทอดเผ็ด (1 ชิ้น)', emoji: '🍗', calories: 370, protein: 24, carbs: 16, fat: 24 },
      { name: 'Texas Chicken Burger', nameTh: 'เท็กซัสชิคเก้น เบอร์เกอร์ไก่', emoji: '🍔', calories: 480, protein: 22, carbs: 44, fat: 24 },
      { name: 'Texas Honey Biscuit', nameTh: 'เท็กซัสชิคเก้น ฮันนี่บิสกิต', emoji: '🧈', calories: 280, protein: 4, carbs: 36, fat: 14, sugar: 8 },
    ],
  },
  {
    label: 'Bar-B-Q Plaza',
    labelTh: 'บาร์บีคิวพลาซ่า',
    emoji: '🥘',
    items: [
      { name: 'BBQ Plaza Pork Set', nameTh: 'บาร์บีคิวพลาซ่า ชุดหมู', emoji: '🥩', calories: 450, protein: 30, carbs: 20, fat: 28 },
      { name: 'BBQ Plaza Beef Set', nameTh: 'บาร์บีคิวพลาซ่า ชุดเนื้อ', emoji: '🥩', calories: 480, protein: 32, carbs: 18, fat: 30 },
      { name: 'BBQ Plaza Seafood Set', nameTh: 'บาร์บีคิวพลาซ่า ชุดทะเล', emoji: '🦐', calories: 350, protein: 28, carbs: 18, fat: 18 },
      { name: 'BBQ Plaza Mixed Set', nameTh: 'บาร์บีคิวพลาซ่า ชุดรวม', emoji: '🥘', calories: 500, protein: 34, carbs: 22, fat: 28 },
      { name: 'BBQ Plaza Sauce (1 cup)', nameTh: 'บาร์บีคิวพลาซ่า น้ำจิ้ม (1 ถ้วย)', emoji: '🥣', calories: 80, protein: 2, carbs: 14, fat: 2 },
      { name: 'BBQ Plaza Vermicelli Soup', nameTh: 'บาร์บีคิวพลาซ่า วุ้นเส้นน้ำ', emoji: '🍲', calories: 180, protein: 8, carbs: 28, fat: 4 },
      { name: 'BBQ Plaza Rice (1 portion)', nameTh: 'บาร์บีคิวพลาซ่า ข้าวสวย', emoji: '🍚', calories: 250, protein: 5, carbs: 55, fat: 1 },
    ],
  },
  {
    label: 'After You & Dessert Cafe',
    labelTh: 'อาฟเตอร์ยูและร้านของหวาน',
    emoji: '🍰',
    items: [
      { name: 'After You Shibuya Toast', nameTh: 'อาฟเตอร์ยู ชิบูย่าโทสต์', emoji: '🍞', calories: 680, protein: 10, carbs: 82, fat: 34, sugar: 45 },
      { name: 'After You Kakigori (shaved ice)', nameTh: 'อาฟเตอร์ยู คากิโกริ (น้ำแข็งไส)', emoji: '🍧', calories: 450, protein: 6, carbs: 70, fat: 16, sugar: 50 },
      { name: 'After You Chocolate Toast', nameTh: 'อาฟเตอร์ยู ช็อกโกแลตโทสต์', emoji: '🍫', calories: 720, protein: 12, carbs: 88, fat: 36, sugar: 42 },
      { name: 'After You Matcha Lava', nameTh: 'อาฟเตอร์ยู มัทฉะลาวา', emoji: '🍵', calories: 520, protein: 8, carbs: 64, fat: 26, sugar: 30 },
      { name: 'After You Croffle', nameTh: 'อาฟเตอร์ยู ครอฟเฟิล', emoji: '🧇', calories: 380, protein: 6, carbs: 46, fat: 20, sugar: 22 },
    ],
  },
];
